import { Container, Header } from 'shared/components/shared';
import { Metadata } from 'next';
// import { Suspense } from 'react';

export const metadata: Metadata = {
    title: 'Next Pizza | Замовлення',
    description: 'Generated by create next app',
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
    return (
        <main className="min-h-screen bg-[#F4F1EE]">
            <Container>
                <Header hasSearch={false} className="border-b-gray-200" />
                {/* <Suspense>
                    <Header hasSearch={false} className="border-b-gray-200" />
                </Suspense> */}
                {children}
            </Container>
        </main>
    );
}